Update ODOO_BASE_DIR attributes and set ODOO_DAEMON_USER as the owner.
bitnami/bitnami-docker-odoo pull request #121
Opened 2022-05-15 20:15 UTC by ruddy32

Signed-off-by: Sylvain Bonnemaison <sylvain.bonnemaison@ti-mm.com>

**Description of the change**

Update `postunpack.sh` shell script with following features :
- update `ODOO_BASE_DIR` directory attributes
- set `ODOO_DAEMON_USER` as the owner of `ODOO_BASE_DIR` directory . 

**Benefits**

`postunpack.sh` script is able to update `ODOO_BASE_DIR` base directory content when running container using  `ODOO_DAEMON_USER` user, instead of `roor` user.

**Applicable issues**

Issue #118

2022-05-17 08:19 UTC, rafariossaa commented
When adding this I got the following error:
```
odoo_1        | odoo 08:19:06.33 INFO  ==> Validating database owner
odoo_1        | odoo 08:19:06.35 INFO  ==> Generating configuration file
odoo_1        | odoo 08:19:06.36 INFO  ==> Installing modules
odoo_1        | error: exec: "/opt/bitnami/odoo/bin/odoo": permission denied
debian-10_odoo_1 exited with code 1
```

2022-05-18 19:49 UTC, ruddy32 commented
The fix has been update to switch ODOO_BASE_DIR owner name to ODOO_DAEMON_USER.

2022-05-25 10:04 UTC, rafariossaa requested changes
Hi,
  The change LGTM, but I would prefer if you use `chown` directly in the postunpack.sh instead of using `owned_by`. It is to be consistent with what we have in other images in postunpack.
  Could you change that ?

2022-05-25 17:29 UTC, ruddy32 commented
> Hi, The change LGTM, but I would prefer if you use `chown` directly in the postunpack.sh instead of using `owned_by`. It is to be consistent with what we have in other images in postunpack. Could you change that ?

I guess that `owned_by` would be the best bitnami practice.
Ok I will switch to `chown`

2022-05-30 10:43 UTC, rafariossaa commented
Hi,
 Thanks for changing it.

2022-05-30 10:43 UTC, merged